#ifndef TTRAINDRIVERCAR_H__
#define TTRAINDRIVERCAR_H__

enum
{
	TRAIN_CAR_PROPERTIES			= 10000,
	TRAIN_CAR_WHEELDISTANCE		= 10001,
	TRAIN_CAR_LENGTH					= 10002
};

#endif // TTRAINDRIVERCAR_H__
