enum
{
	IDS_TRAINDRIVERMAIN	= 10000,
	IDS_TRAINDRIVERCAR,
	IDS_TRAIN_INFO_CARCOUNT,
	IDS_TRAIN_INFO_TRACKLENGTH,
	IDS_TRAIN_INFO_ERROR_CAR,
	IDS_TRAIN_INFO_ERROR_PATHLENGTH,
	IDS_TRAIN_INFO_ERROR_NOCARS,
	IDS_TRAIN_OP_CAR,
	IDS_TRAIN_OP_MAIN,
	IDS_TRAIN_OP_WHEEL,

	_DUMMY_ELEMENT_
};
