enum
{
	// string table definitions
	IDS_TRAINDRIVERMAIN	= 10000,
	IDS_TRAINDRIVERCAR,
	TRAIN_INFO_CARCOUNT,
	TRAIN_INFO_TRACKLENGTH,
	TRAIN_INFO_ERROR_CAR,
	TRAIN_INFO_ERROR_PATHLENGTH,
	TRAIN_INFO_ERROR_NOCARS,
	TRAIN_OP_CAR,
	TRAIN_OP_MAIN,
	TRAIN_OP_WHEEL,

// End of symbol definition
  _DUMMY_ELEMENT_
};
